name: Cypress Tests 
on:
  push:
    branches:
      - 'main'  
jobs:
  build:

    runs-on: 
      labels: ubuntu-latest

    strategy:
      matrix:
        browser:
          - chrome  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build and run Cypress tests
        run: |
          docker build -t my-cypress-image -f Dockerfile --build-arg BROWSER=${{ matrix.browser }} .
          docker run --rm  \
            -v $(pwd)/public/screenshots:/Top99TestAutomation/cypress/screenshots \
            -v $(pwd)/public/videos:/Top99TestAutomation/cypress/videos my-cypress-image          
        env:
          CI: true
          BROWSER: ${{ matrix.browser }}

      - name: Merge test reports
        run: npm run combine:report

      - name: Generate HTML report
        run: npm run generate:report
      
      - name: Deploy report page to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public